### PR TITLE
Throw an Error which contains the filePath when parsing fails

### PR DESCRIPTION
**Pull request by simonexmachina**
...so that developer has some idea where it came from.

### CODE REVIEW

**Comment by jgable** [comment]
Thanks for the PR.  I think it's a little aggressive to wrap that much code in a try/catch.  Why not try to figure out the most likely place an error will be thrown and just limit it to that.  Like, in the `getContentsSyntaxTree` function where the `esprima.parse()` call is.

**Comment by jgable** [comment]
Covered this in 215f32c and added a unit test.  Published as 0.0.10.  Thanks for the suggestion to add this and for the original PR.

**Comment by simonexmachina** [comment]
Thanks.

**Comment by simonexmachina** [comment]
@jgable would you please update this in broccoli-es6-import-validate so I can send a PR to update in ember-cli. Thanks.

**Comment by jgable** [comment]
All you have to do is run `npm update` and it will update the version you have installed.  If you're installing from new, it should install the latest.

The magic of correctly used semantic versioning.

**Comment by simonexmachina** [comment]
Ah yes! Good point :)​

**Pull request closed without merging**
